### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by lopuhin** [recursionpharma/rxrx1-utils#3]
Hi, I'm taking part in https://www.kaggle.com/c/recursion-cellular-image-classification/ and find this code very helpful and would like to use some parts of it in my solution. But I didn't find any information about the license, could you please clarify it?

**Comment by bmabey** [comment]
Ah, sorry about that, I forgot to add it. I just did. The license is Apache 2.0. Thanks for opening this issue!
