### ISSUE TITLE
by_exp_plate_site-42 directory structure

### ISSUE THREAD

**Issue by cxz** [recursionpharma/rxrx1-utils#4]
The README says there would be train/test sub-directories under "by_exp_plate_site-42", but apparently that's not the case.

```
gsutil ls -l gs://rxrx1-us-central1/tfrecords/by_exp_plate_site-42
```

**Comment by bmabey** [comment]
Thanks for reporting this discrepancy. I'm updated the README in 501599040b17600e635b3188041332cee1386a65 to reflect the actual structure.
